worker_processes  1;
daemon off;
error_log  /Volumes/Crucial X6/Projects/Trace2Pass/evaluation/projects/nginx/scripts/../nginx-error.log  info;
pid        /Volumes/Crucial X6/Projects/Trace2Pass/evaluation/projects/nginx/scripts/../nginx.pid;

events {
    worker_connections  1024;
}

http {
    access_log  /Volumes/Crucial X6/Projects/Trace2Pass/evaluation/projects/nginx/scripts/../nginx-access.log;

    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   /Volumes/Crucial X6/Projects/Trace2Pass/evaluation/projects/nginx/scripts/../html;
            index  index.html;
        }
    }
}
